# Generated by Django 2.2.4 on 2019-08-02 23:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import pets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=pets.models.get_image_path)),
            ],
        ),
    ]
