# Generated by Django 2.2.4 on 2019-08-03 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='profile_image',
            new_name='pet_image',
        ),
    ]
