# Generated by Django 2.2.4 on 2019-08-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20190803_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos'),
        ),
    ]
